dataset_path = "dataset/k1"
kfold = 1
target_type = "Green"
tile_size = 256
lr = 5e-5
loss_func = "F1"
num_epochs = 100
target_size = 256
batch_size = 8
checkpoint_path = "results/experiment_20230123_031334"
model_path = ""
transform_name = "non_spatial_E"
freeze_pretrained = true
pretrained_type = "resnet50"
signal_fraction = 0.5
num_classes = 2
alt_validation_path = ""
early_stopping = "val loss"
focal_gamma = 1
weight = [ "0.5102716855331277", "24.83875133674144",]
resampling_method = "signal"
early_stopping_window = 5
edge_excluded = true
