dataset_path = "dataset/k1"
kfold = 1
target_type = "Green"
tile_size = 256
lr = 0.0005
loss_func = "Focal"
num_epochs = 100
target_size = 256
batch_size = 8
checkpoint_path = "results/experiment_20221215_181131"
model_path = ""
transform_name = "no_augs_A"
freeze_pretrained = true
pretrained_type = "resnet50"
signal_fraction = 0.25
num_classes = 2
alt_validation_path = ""
early_stopping = "val loss"
focal_gamma = 1
weight = [ "0.5050877146591881", "49.637975839213716",]
resampling_method = "background"
early_stopping_window = 5
