dataset_path = "alt_dataset/k1"
kfold = 1
target_type = "Green"
tile_size = 256
lr = 5e-5
loss_func = "F1"
num_epochs = 100
target_size = 256
batch_size = 8
checkpoint_path = "alt_results/alt_experiment_20230125_143332"
model_path = ""
transform_name = "non_spatial_E"
freeze_pretrained = true
pretrained_type = "resnet50"
signal_fraction = 0.5
num_classes = 2
alt_validation_path = ""
early_stopping = "val loss"
focal_gamma = 1
weight = [ "0.5097148245027037", "26.23386682697408",]
resampling_method = "signal"
early_stopping_window = 5
edge_excluded = true
